# The domain I got for the website
baseURL: https://bravegrape.dev
languageCode: en-uk
defaultContentLanguage: en

# This will be the title of the website
title: Technically writing

# Using 'cupper' which is the name I have the theme when importing it
# I replaced 'cupper-hugo-theme' which  is the name of the repo for the theme
theme: cupper
googleAnalytics:

# Add explanation for this!
taxonomies:
  tag: tags

# Add explanation for this!
permalinks:
  post: /:filename/

# Add explanation for this!
imaging:
  quality: 99

params:
  description: An accessibility-friendly Hugo theme, ported from the [original Cupper](https://github.com/ThePacielloGroup/cupper) project.
  homeMetaContent: An accessibility-friendly Hugo theme, ported from the original Cupper project.
  footer: Website made with [Hugo](https://gohugo.io/), themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme), and deployed to [Netlify](https://www.netlify.com/).
  # For more date formats see https://gohugo.io/functions/format/
  # Those date formats make veery little sense
  dateFormat: Jan 2, 2006
  codePenUser: someUser

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /post/
      weight: 2
    - name: Tags
      url: /tags/
      weight: 3
    - name: About
      url: /about/
      weight: 4
