#baseURL = "bravegrape.dev"
relativeurls = true
languageCode = "en-uk"
defaultContentLanguage = "en"
title = "Technically writing"
theme = "cupper-hugo-theme"
# Added token I got with my Analytics account
googleAnalytics = "UA-109269946-1"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
  description = "A scientist does some technical writing and other things..."
  homeMetaContent = "A scientist does some technical writing and other things..."
  footer = "Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed to [Netlify](https://www.netlify.com/)."
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "Jan 2, 2006"
  codePenUser = "someUser"

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Blog"
    url = "/post/"
    weight = 2
  [[menu.nav]]
    name = "Korean"
    url = "/korean/"
    weight = 3
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 4
